import { useEffect, useState } from 'react'
import { NavLink, Outlet, useLocation } from 'react-router-dom'

function Layout() {
  const [dark, setDark] = useState(() => localStorage.getItem('pokedex-theme') !== 'light')
  const location = useLocation()
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('pokedex-theme', dark ? 'dark' : 'light') }, [dark])
  return <div className="app-shell"><header className="app-header"><div className="app-header-inner"><NavLink to="/" className="brand" aria-label="PokéDex Nexus home"><span className="brand-mark"><span /></span><span><strong className="brand-name">PokéDex <em>NEXUS</em></strong><small>interactive field system</small></span></NavLink><div className="system-status"><i/> <span>FIELD LINK ONLINE</span><b>DEX 1–1025+</b></div><nav className="top-nav" aria-label="Primary navigation"><NavLink className={({ isActive }) => `nav-link ${isActive && location.pathname === '/' ? 'is-active' : ''}`} to="/">Discover</NavLink><NavLink className={({ isActive }) => `nav-link ${isActive ? 'is-active' : ''}`} to="/favorites">Favorites</NavLink><NavLink className={({ isActive }) => `nav-link ${isActive ? 'is-active' : ''}`} to="/compare">Compare</NavLink><NavLink className={({ isActive }) => `nav-link nav-game ${isActive ? 'is-active' : ''}`} to="/battle">Battle</NavLink><NavLink className={({ isActive }) => `nav-link ${isActive ? 'is-active' : ''}`} to="/team">Team</NavLink><NavLink className={({ isActive }) => `nav-link ${isActive ? 'is-active' : ''}`} to="/types">Types</NavLink></nav><nav className="mobile-nav" aria-label="Mobile navigation"><NavLink to="/">⌂<small>Home</small></NavLink><NavLink to="/compare">◈<small>Compare</small></NavLink><NavLink to="/team">◇<small>Team</small></NavLink><NavLink to="/battle">⚡<small>Battle</small></NavLink><NavLink to="/types">◌<small>Types</small></NavLink></nav><button className="theme-button" type="button" aria-label="Toggle color theme" onClick={() => setDark((value) => !value)}><span aria-hidden="true">{dark ? '☀' : '☾'}</span><span className="theme-label">{dark ? 'Light' : 'Dark'}</span></button></div></header><main className="page-shell"><Outlet /></main><footer className="site-footer"><div><strong>PokéDex NEXUS</strong><span>React · Vite · PokéAPI · open community assets</span></div><span>Research. Compare. Battle. Discover.</span></footer></div>
}
export default Layout
